### ISSUE TITLE
Research different types of mobile games 

### ISSUE THREAD

**Issue by djw135** [CS3398-Latte-Wizards/cs3398-latte-f2017#2]
Research different types of games and pitch ideas based off of difficulty.

**Comment by jmass1991** [comment]
There are many ways we could viably do an arcade or bullet hell mobile game. All the ways I saw involved using a game engine with a blueprint of sorts. As far as writing the engine ourselves for  a mobile game could be difficult, but I have never done it so I can't really say. I watched a tutorial on making a game engine in java for a desktop app  and it seemed very time consuming to produce something small. My vote is for an arcade game simply because I  would enjoy working on it more over the text based.
